name: CI Fullstack Workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v4
      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - run: npm install
        working-directory: ./backend

      # Run the tests.
      - run: node test.js
        working-directory: ./backend

      # Run the linter (syntax check).
      - run: node -c app.js && node -c test.js
        working-directory: ./backend

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
